spring :
    application:
       name: stream-hello
    rabbitmq :
       host : 192.168.40.91
       port : 5672
#       username: guest
#       password: guest
server :
    port: 9071


