spring :
    application:
       name: stream-hello
    rabbitmq :
       host : 192.168.40.91
       port : 5672
#       username: guest
#       password: guest
    cloud:
       stream:
          bindings:
             input:
                group: group-a
server :
    port: 9071


