server:
    port: 9001

eureka:
    instance:
       hostname: eurekaserver
       prefer-ip-address: true
    client:
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl.defaultZone: http://eurekaserver:9002/eureka/
