spring:
   application:
      name: gateway
server:
   port: 9031
eureka:
   client:
      serviceUrl.defaultZone: http://localhost:9001/eureka/
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 10000
#zuul:
#   host:
#     connect-timeout-millis: 60000
#     socket-timeout-millis: 60000

ribbon:
   ConnectTimeout: 10000
   ReadTimeout: 10000

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds   默认一秒