spring:
   application:
      name: gateway
#spring.cloud.loadbalancer.retry.enabled=true
zuul:
   retryable: true
#   routes:
#      consumer-feign: /consumer-feign/**


#   host:
#     connect-timeout-millis: 60000
#     socket-timeout-millis: 60000

server:
   port: 9031

eureka:
   client:
      serviceUrl:
         defaultZone: http://eurekaserver:9001/eureka/,http://eurekaserver.com:9002/eureka/
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds:20000
#CommonClientConfigKey
ribbon:
   ConnectTimeout: 20000
   ReadTimeout: 2000
   MaxAutoRetries: 1
   MaxAutoRetriesNextServer: 1
#ribbon.okToRetryOnAllOperations=true

#HystrixCommandProperties
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds   默认一秒