spring:
   application:
      name: service-a
server:
   port: 9011
 #  port: ${random.int[10000,19999]}

eureka:
   client:
      serviceUrl.defaultZone: http://eurekaserver:9001/eureka/,http://www.host2.com:9002/eureka/
